### ISSUE TITLE
duplicated usbx_stm32_device_controllers folder

### ISSUE THREAD

**Issue by ayedm1** [STMicroelectronics/stm32-mw-usbx#1]
duplicated folder usbx_stm32_device_controllers in [Release v6.4.0_240419](https://github.com/STMicroelectronics/stm32_mw_usbx/commit/e14af8bcebfb49f3de9af7faf4f0e1ec8cff0a27)

https://github.com/STMicroelectronics/stm32_mw_usbx/tree/main/usbx_stm32_device_controllers-29f8d36

https://github.com/STMicroelectronics/stm32_mw_usbx/tree/main/common/usbx_stm32_device_controllers

**Comment by rahmanih** [comment]
Fixed it.
